import globals from "globals";
import jsdoc from "eslint-plugin-jsdoc";
import jest from "eslint-plugin-jest";
import stylistic from '@stylistic/eslint-plugin';

export default [
    {
        files: ["src/js/**/*.js"],
        languageOptions: {
            ecmaVersion: 5,
            sourceType: "script",
            globals: {
                ...globals.browser,
                Promise: "off"
            },
        },
        plugins: {
            jsdoc: jsdoc,
            stylistic: stylistic,
        },
        rules: {
            // eslint:all
            "accessor-pairs": "off",
            "array-callback-return": "error",
            "arrow-body-style": ["error", "always"],
            "block-scoped-var": "error",
            "camelcase": "error",
            "capitalized-comments": ["error", "always", {"ignorePattern": "region|endregion"}],
            "class-methods-use-this": "off",
            "complexity": ["error", {"max": 25}],
            "consistent-return": "error",
            "consistent-this": ["error", "that"],
            "constructor-super": "error",
            "curly": "error",
            "default-case": "error",
            "default-case-last": "error",
            "default-param-last": "error",
            "dot-notation": "error",
            "eqeqeq": ["error", "always"],
            "for-direction": "error",
            "func-name-matching": "error",
            "func-names": ["error", "always"],
            "func-style": ["error", "declaration", {"allowArrowFunctions": false}],
            "getter-return": "error",
            "grouped-accessor-pairs": "error",
            "guard-for-in": "error",
            "id-denylist": "off",
            "id-length": ["error", {"min": 2, "exceptions": ["x", "y"]}],
            "id-match": "off",
            "init-declarations": ["off"],
            "logical-assignment-operators": ["error", "never"],
            "max-classes-per-file": ["error", 1],
            "max-depth": ["error", 5],
            "max-lines": ["error", {"max": 750, "skipBlankLines": true, "skipComments": true}],
            "max-lines-per-function": ["error", {"max": 100, "skipBlankLines": true, "skipComments": true}],
            "max-nested-callbacks": ["error", 10],
            "max-params": ["error", 4],
            "max-statements": ["error", 50],
            "new-cap": "error",
            "no-alert": "error",
            "no-array-constructor": "error",
            "no-async-promise-executor": "error",
            "no-await-in-loop": "error",
            "no-bitwise": ["error", {"allow": [">>"], "int32Hint": true}],
            "no-caller": "error",
            "no-case-declarations": "error",
            "no-class-assign": "error",
            "no-compare-neg-zero": "error",
            "no-cond-assign": ["error", "always"],
            "no-console": "error",
            "no-const-assign": "error",
            "no-constant-binary-expression": "error",
            "no-constant-condition": ["error", {"checkLoops": "all"}],
            "no-constructor-return": "error",
            "no-continue": "off",
            "no-control-regex": "error",
            "no-debugger": "error",
            "no-delete-var": "error",
            "no-div-regex": "error",
            "no-dupe-args": "error",
            "no-dupe-class-members": "error",
            "no-dupe-else-if": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",
            "no-duplicate-imports": "error",
            "no-else-return": "error",
            "no-empty": "error",
            "no-empty-character-class": "error",
            "no-empty-function": "error",
            "no-empty-pattern": "error",
            "no-empty-static-block": "error",
            "no-eq-null": "error",
            "no-eval": "error",
            "no-ex-assign": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-boolean-cast": ["error", {"enforceForLogicalOperands": true}],
            "no-extra-label": "error",
            "no-fallthrough": "error",
            "no-func-assign": "error",
            "no-global-assign": "error",
            "no-implicit-coercion": "error",
            "no-implicit-globals": "off",
            "no-implied-eval": "error",
            "no-import-assign": "error",
            "no-inline-comments": ["error", {"ignorePattern": "BUILD REMOVE LINE"}],
            "no-inner-declarations": ["error", "functions", {"blockScopedFunctions": "disallow"}],
            "no-invalid-regexp": "error",
            "no-invalid-this": "error",
            "no-irregular-whitespace": "error",
            "no-iterator": "error",
            "no-label-var": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-loop-func": "error",
            "no-loss-of-precision": "error",
            "no-magic-numbers": ["error", {"ignore": [0, 1, -1, 2, 4, 8, 12, 16], "ignoreArrayIndexes": true, "ignoreDefaultValues": true}],
            "no-misleading-character-class": "error",
            "no-multi-assign": "error",
            "no-multi-str": "error",
            "no-negated-condition": "error",
            "no-nested-ternary": "error",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-native-nonconstructor": "error",
            "no-new-wrappers": "error",
            "no-nonoctal-decimal-escape": "error",
            "no-obj-calls": "error",
            "no-object-constructor": "error",
            "no-octal": "error",
            "no-octal-escape": "error",
            "no-param-reassign": "error",
            "no-plusplus": ["error", {"allowForLoopAfterthoughts": true}],
            "no-promise-executor-return": "error",
            "no-proto": "error",
            "no-prototype-builtins": "error",
            "no-redeclare": "error",
            "no-regex-spaces": "error",
            "no-restricted-exports": "error",
            "no-restricted-globals": "error",
            "no-restricted-imports": "error",
            "no-restricted-properties": "error",
            "no-restricted-syntax": "error",
            "no-return-assign": "error",
            "no-script-url": "error",
            "no-self-assign": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-setter-return": "error",
            "no-shadow": "error",
            "no-shadow-restricted-names": "error",
            "no-sparse-arrays": "error",
            "no-template-curly-in-string": "error",
            "no-ternary": "error",
            "no-this-before-super": "error",
            "no-throw-literal": "error",
            "no-undef": "error",
            "no-undef-init": "error",
            "no-undefined": "off",
            "no-underscore-dangle": "error",
            "no-unexpected-multiline": "error",
            "no-unmodified-loop-condition": "error",
            "no-unneeded-ternary": "error",
            "no-unreachable": "error",
            "no-unreachable-loop": "error",
            "no-unsafe-finally": "error",
            "no-unsafe-negation": "error",
            "no-unsafe-optional-chaining": "error",
            "no-unused-expressions": "error",
            "no-unused-labels": "error",
            "no-unused-private-class-members": "error",
            "no-unused-vars": "error",
            "no-use-before-define": ["error", {"functions": false, "classes": true, "variables": true}],
            "no-useless-assignment": "error",
            "no-useless-backreference": "error",
            "no-useless-call": "error",
            "no-useless-catch": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-useless-escape": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "off",
            "no-void": "error",
            "no-warning-comments": "error",
            "no-with": "error",
            "object-shorthand": ["error", "never"],
            "one-var": ["error", "never"],
            "operator-assignment": ["error", "never"],
            "prefer-arrow-callback": "off",
            "prefer-const": "off",
            "prefer-destructuring": "off",
            "prefer-exponentiation-operator": "off",
            "prefer-named-capture-group": "off",
            "prefer-numeric-literals": "error",
            "prefer-object-has-own": "off",
            "prefer-object-spread": "off",
            "prefer-promise-reject-errors": "off",
            "prefer-regex-literals": "error",
            "prefer-rest-params": "off",
            "prefer-spread": "off",
            "prefer-template": "off",
            "radix": ["error", "always"],
            "require-atomic-updates": "error",
            "require-await": "error",
            "require-unicode-regexp": "off",
            "require-yield": "error",
            "sort-imports": "error",
            "sort-keys": ["off"],
            "sort-vars": ["off"],
            "strict": "off",
            "symbol-description": "off",
            "unicode-bom": ["error", "never"],
            "use-isnan": "error",
            "valid-typeof": "error",
            "vars-on-top": "error",
            "yoda": "error",
            // eslint-stylistic:all
            "stylistic/array-bracket-newline": ["error", "consistent"],
            "stylistic/array-bracket-spacing": ["error", "never"],
            "stylistic/array-element-newline": ["error", "consistent"],
            "stylistic/arrow-parens": ["error", "always"],
            "stylistic/arrow-spacing": ["error", {"before": true, "after": true}],
            "stylistic/block-spacing": ["error", "always"],
            "stylistic/brace-style": ["error", "1tbs", {"allowSingleLine": false}],
            "stylistic/comma-dangle": ["error", "never"],
            "stylistic/comma-spacing": ["error", {"before": false, "after": true}],
            "stylistic/comma-style": ["error", "last"],
            "stylistic/computed-property-spacing": ["error", "never"],
            "stylistic/dot-location": ["error", "object"],
            "stylistic/eol-last": ["error", "always"],
            "stylistic/function-call-argument-newline": ["error", "consistent"],
            "stylistic/function-call-spacing": ["error", "never"],
            "stylistic/function-paren-newline": ["error", "consistent"],
            "stylistic/generator-star-spacing": ["error",
                {
                    "before": false,
                    "after": true,
                    "anonymous": {"before": false, "after": true},
                    "method": {"before": true, "after": false}
                }
            ],
            "stylistic/implicit-arrow-linebreak": ["error", "beside"],
            "stylistic/indent": ["error", 4],
            "stylistic/indent-binary-ops": ["error", 4],
            "stylistic/key-spacing": ["error",
                {
                    "beforeColon": false,
                    "afterColon": true,
                    "mode": "minimum",
                    align: {
                        "beforeColon": false,
                        "afterColon": true,
                        "on": "colon",
                        "mode": "minimum"
                    }
                }
            ],
            "stylistic/keyword-spacing": ["error", {"before": true, "after": true}],
            "stylistic/line-comment-position": ["error", {"position": "above", "ignorePattern": "BUILD REMOVE LINE"}],
            "stylistic/linebreak-style": ["error", "unix"],
            "stylistic/lines-around-comment": ["error",
                {
                    "beforeBlockComment": true,
                    "afterBlockComment": false,
                    "beforeLineComment": true,
                    "afterLineComment": false,
                    "allowBlockStart": true,
                    "allowBlockEnd": false,
                    "allowClassStart": true,
                    "allowClassEnd": false,
                    "allowObjectStart": true,
                    "allowObjectEnd": false,
                    "allowArrayStart": true,
                    "allowArrayEnd": false,
                    "ignorePattern": "region|endregion|type"
                }
            ],
            "stylistic/lines-between-class-members": ["error", "always"],
            "stylistic/max-len": ["error",
                {
                    "code": 180,
                    "comments": 180,
                    "ignorePattern": "global",
                    "ignoreRegExpLiterals": true,
                    "ignoreStrings": true,
                    "ignoreTemplateLiterals": true,
                    "ignoreTrailingComments": true,
                    "ignoreUrls": true
                }
            ],
            "stylistic/max-statements-per-line": ["error", {"max": 1}],
            "stylistic/member-delimiter-style": ["error",
                {
                    "multiline": {
                        "delimiter": "comma",
                        "requireLast": false
                    },
                    "singleline": {
                        "delimiter": "comma",
                        "requireLast": false
                    },
                }
            ],
            "stylistic/multiline-comment-style": ["error", "starred-block"],
            "stylistic/multiline-ternary": ["error", "always-multiline"],
            "stylistic/new-parens": ["error", "always"],
            "stylistic/newline-per-chained-call": ["error", {"ignoreChainWithDepth": 5}],
            "stylistic/no-confusing-arrow": ["error", {"allowParens": false, "onlyOneSimpleParam": false}],
            "stylistic/no-extra-parens": "off",
            "stylistic/no-extra-semi": "error",
            "stylistic/no-floating-decimal": "error",
            "stylistic/no-mixed-operators": ["error", {"allowSamePrecedence": false}],
            "stylistic/no-mixed-spaces-and-tabs": "error",
            "stylistic/no-multi-spaces": ["error", {"ignoreEOLComments": false, "exceptions": {"Property": true}}],
            "stylistic/no-multiple-empty-lines": ["error", {"max": 1, "maxBOF": 0, "maxEOF": 1}],
            "stylistic/no-tabs": ["error", {"allowIndentationTabs": false}],
            "stylistic/no-trailing-spaces": ["error", {"ignoreComments": false, "skipBlankLines": false}],
            "stylistic/no-whitespace-before-property": "error",
            "stylistic/nonblock-statement-body-position": ["error", "below"],
            "stylistic/object-curly-newline": ["error", {"consistent": true}],
            "stylistic/object-curly-spacing": ["error", "never"],
            "stylistic/object-property-newline": ["error", {"allowAllPropertiesOnSameLine": true}],
            "stylistic/one-var-declaration-per-line": ["error", "always"],
            "stylistic/operator-linebreak": ["error", "after"],
            "stylistic/padded-blocks": ["error", "never"],
            "stylistic/padding-line-between-statements": ["error"],
            "stylistic/quote-props": ["error", "consistent-as-needed", {"keywords": true, "numbers": true}],
            "stylistic/quotes": ["error", "double"],
            "stylistic/rest-spread-spacing": ["error", "never"],
            "stylistic/semi": ["error", "always"],
            "stylistic/semi-spacing": ["error", {"before": false, "after": true}],
            "stylistic/semi-style": ["error", "last"],
            "stylistic/space-before-blocks": ["error"],
            "stylistic/space-before-function-paren": ["error", "never"],
            "stylistic/space-in-parens": ["error", "never"],
            "stylistic/space-infix-ops": ["error", {"int32Hint": false}],
            "stylistic/space-unary-ops": ["error"],
            "stylistic/spaced-comment": ["error", "always"],
            "stylistic/switch-colon-spacing": ["error", {"after": true, "before": false}],
            "stylistic/template-curly-spacing": ["error", "never"],
            "stylistic/template-tag-spacing": ["error", "never"],
            "stylistic/wrap-iife": ["error", "outside"],
            "stylistic/wrap-regex": "error",
            "stylistic/yield-star-spacing": ["error", {"before": false, "after": true}],
            // jsdoc:all
            "jsdoc/check-access": "error",
            "jsdoc/check-alignment": "error",
            "jsdoc/check-examples": "off",
            "jsdoc/check-indentation": "off",
            "jsdoc/check-line-alignment": ["error", "always", {"tags": ["param", "property"]}],
            "jsdoc/check-param-names": ["error", {"enableFixer": true, "checkDestructured": true, "useDefaultObjectProperties": true, "disableExtraPropertyReporting": true}],
            "jsdoc/check-property-names": ["error", {"enableFixer": true}],
            "jsdoc/check-syntax": "error",
            "jsdoc/check-tag-names": "error",
            "jsdoc/check-types": "error",
            "jsdoc/check-values": ["error"],
            "jsdoc/empty-tags": "error",
            "jsdoc/implements-on-classes": "error",
            "jsdoc/imports-as-dependencies": "error",
            "jsdoc/match-description": "error",
            "jsdoc/match-name": "off",
            "jsdoc/multiline-blocks": "error",
            "jsdoc/no-bad-blocks": "error",
            "jsdoc/no-blank-block-descriptions": "error",
            "jsdoc/no-blank-blocks": "error",
            "jsdoc/no-defaults": "error",
            "jsdoc/no-missing-syntax": "off",
            "jsdoc/no-multi-asterisks": "error",
            "jsdoc/no-restricted-syntax": "off",
            "jsdoc/no-types": "off",
            "jsdoc/no-undefined-types": "error",
            "jsdoc/require-asterisk-prefix": ["error", "always"],
            "jsdoc/require-description": "error",
            "jsdoc/require-description-complete-sentence": "off",
            "jsdoc/require-example": "off",
            "jsdoc/require-file-overview": "off",
            "jsdoc/require-hyphen-before-param-description": ["error", "always"],
            "jsdoc/require-jsdoc": "error",
            "jsdoc/require-param": "error",
            "jsdoc/require-param-description": "error",
            "jsdoc/require-param-name": "error",
            "jsdoc/require-param-type": "error",
            "jsdoc/require-property": "error",
            "jsdoc/require-property-description": "error",
            "jsdoc/require-property-name": "error",
            "jsdoc/require-property-type": "error",
            "jsdoc/require-returns": "error",
            "jsdoc/require-returns-check": "error",
            "jsdoc/require-returns-description": "off",
            "jsdoc/require-returns-type": "error",
            "jsdoc/require-throws": "error",
            "jsdoc/require-yields": "error",
            "jsdoc/require-yields-check": "error",
            "jsdoc/sort-tags": ["error", {"tagSequence": [
                {tags: [
                        // Brief descriptions
                        "summary",
                        "typeSummary",

                        // Module/file-level
                        "module",
                        "exports",
                        "file",
                        "fileoverview",
                        "overview",
                        "import",

                        // Identifying (name, type)
                        "typedef",
                        "interface",
                        "record",
                        "template",
                        "name",
                        "kind",
                        "type",
                        "alias",
                        "external",
                        "host",
                        "callback",
                        "func",
                        "function",
                        "method",
                        "class",
                        "constructor",

                        // Relationships
                        "modifies",
                        "mixes",
                        "mixin",
                        "mixinClass",
                        "mixinFunction",
                        "namespace",
                        "borrows",
                        "constructs",
                        "lends",
                        "implements",
                        "requires",

                        // Long descriptions
                        "desc",
                        "description",
                        "classdesc",
                        "tutorial",
                        "copyright",
                        "license",

                        // Simple annotations
                        "const",
                        "constant",
                        "final",
                        "global",
                        "readonly",
                        "abstract",
                        "virtual",
                        "var",
                        "member",
                        "memberof",
                        "memberof!",
                        "inner",
                        "instance",
                        "inheritdoc",
                        "inheritDoc",
                        "override",
                        "hideconstructor",

                        // Core function/object info
                        "param",
                        "arg",
                        "argument",
                        "prop",
                        "property",
                        "return",
                        "returns",

                        // Important behavior details
                        "async",
                        "generator",
                        "default",
                        "defaultvalue",
                        "enum",
                        "augments",
                        "extends",
                        "throws",
                        "exception",
                        "yield",
                        "yields",
                        "event",
                        "fires",
                        "emits",
                        "listens",
                        "this",

                        // Access
                        "static",
                        "private",
                        "protected",
                        "public",
                        "access",
                        "package",

                        "-other",

                        // Supplementary descriptions
                        "see",
                        "example",

                        // METADATA

                        // Other Closure (undocumented) metadata
                        "closurePrimitive",
                        "customElement",
                        "expose",
                        "hidden",
                        "idGenerator",
                        "meaning",
                        "ngInject",
                        "owner",
                        "wizaction",

                        // Other Closure (documented) metadata
                        "define",
                        "dict",
                        "export",
                        "externs",
                        "implicitCast",
                        "noalias",
                        "nocollapse",
                        "nocompile",
                        "noinline",
                        "nosideeffects",
                        "polymer",
                        "polymerBehavior",
                        "preserve",
                        "struct",
                        "suppress",
                        "unrestricted",

                        // @homer0/prettier-plugin-jsdoc metadata
                        "category",

                        // Non-Closure metadata
                        "ignore",
                        "author",
                        "version",
                        "variation",
                        "since",
                        "deprecated",
                        "todo",
                    ]}
                ]}],
            "jsdoc/tag-lines": ["error", "any", {"startLines": 1}],
            "jsdoc/text-escaping": "off",
            "jsdoc/valid-types": "off"
        },
    },
    {
        files: ["tests/*.js"],
        languageOptions: {
            ecmaVersion: "latest",
            globals: {
                ...globals.browser,
                ...globals.jest,
                ...globals.es2015,
                ...globals.node,
                Promise: "off",
            },
        },
        plugins: {
            jest: jest,
            stylistic: stylistic,
        },
        rules: {
            // eslint:recommended
            "constructor-super": "error",
            "for-direction": "error",
            "getter-return": "error",
            "no-async-promise-executor": "error",
            "no-case-declarations": "error",
            "no-class-assign": "error",
            "no-compare-neg-zero": "error",
            "no-cond-assign": "error",
            "no-const-assign": "error",
            "no-constant-binary-expression": "error",
            "no-constant-condition": "error",
            "no-control-regex": "error",
            "no-debugger": "error",
            "no-delete-var": "error",
            "no-dupe-args": "error",
            "no-dupe-class-members": "error",
            "no-dupe-else-if": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",
            "no-empty": "error",
            "no-empty-character-class": "error",
            "no-empty-pattern": "error",
            "no-empty-static-block": "error",
            "no-ex-assign": "error",
            "no-extra-boolean-cast": "error",
            "no-fallthrough": "error",
            "no-func-assign": "error",
            "no-global-assign": "error",
            "no-import-assign": "error",
            "no-invalid-regexp": "error",
            "no-irregular-whitespace": "error",
            "no-loss-of-precision": "error",
            "no-misleading-character-class": "error",
            "no-new-native-nonconstructor": "error",
            "no-nonoctal-decimal-escape": "error",
            "no-obj-calls": "error",
            "no-octal": "error",
            "no-prototype-builtins": "error",
            "no-redeclare": "error",
            "no-regex-spaces": "error",
            "no-self-assign": "error",
            "no-setter-return": "error",
            "no-shadow-restricted-names": "error",
            "no-sparse-arrays": "error",
            "no-this-before-super": "error",
            "no-undef": "error",
            "no-unexpected-multiline": "error",
            "no-unreachable": "error",
            "no-unsafe-finally": "error",
            "no-unsafe-negation": "error",
            "no-unsafe-optional-chaining": "error",
            "no-unused-labels": "error",
            "no-unused-private-class-members": "error",
            "no-unused-vars": "error",
            "no-useless-backreference": "error",
            "no-useless-catch": "error",
            "no-useless-escape": "error",
            "no-with": "error",
            "require-yield": "error",
            "use-isnan": "error",
            "valid-typeof": "error",
            // eslint-stylistic:recommended
            "stylistic/array-bracket-spacing": ["error", "never"],
            "stylistic/arrow-parens": ["error", "always"],
            "stylistic/arrow-spacing": ["error", {"before": true, "after": true}],
            "stylistic/block-spacing": ["error", "always"],
            "stylistic/brace-style": ["error", "1tbs", {"allowSingleLine": true}],
            "stylistic/comma-dangle": ["error", "never"],
            "stylistic/comma-spacing": ["error", {"before": false, "after": true}],
            "stylistic/comma-style": ["error", "last"],
            "stylistic/computed-property-spacing": ["error", "never"],
            "stylistic/dot-location": ["error", "object"],
            "stylistic/eol-last": ["error", "always"],
            "stylistic/indent": ["error", 4],
            "stylistic/indent-binary-ops": ["error", 4],
            "stylistic/key-spacing": ["error",
                {
                    "beforeColon": false,
                    "afterColon": true,
                    "mode": "minimum",
                    align: {
                        "beforeColon": false,
                        "afterColon": true,
                        "on": "colon",
                        "mode": "minimum"
                    }
                }
            ],
            "stylistic/keyword-spacing": ["error", {"before": true, "after": true}],
            "stylistic/lines-between-class-members": ["error", "always"],
            "stylistic/max-statements-per-line": ["error", {"max": 1}],
            "stylistic/member-delimiter-style": ["error",
                {
                    "multiline": {
                        "delimiter": "comma",
                        "requireLast": false
                    },
                    "singleline": {
                        "delimiter": "comma",
                        "requireLast": false
                    },
                }
            ],
            "stylistic/multiline-ternary": ["error", "always-multiline"],
            "stylistic/new-parens": ["error", "always"],
            "stylistic/no-extra-parens": "off",
            "stylistic/no-floating-decimal": "error",
            "stylistic/no-mixed-operators": ["error", {"allowSamePrecedence": false}],
            "stylistic/no-mixed-spaces-and-tabs": "error",
            "stylistic/no-multi-spaces": ["error", {"ignoreEOLComments": false, "exceptions": {"Property": true}}],
            "stylistic/no-multiple-empty-lines": ["error", {"max": 1, "maxBOF": 0, "maxEOF": 1}],
            "stylistic/no-tabs": ["error", {"allowIndentationTabs": false}],
            "stylistic/no-trailing-spaces": ["error", {"ignoreComments": false, "skipBlankLines": false}],
            "stylistic/no-whitespace-before-property": "error",
            "stylistic/object-curly-spacing": ["error", "never"],
            "stylistic/operator-linebreak": ["error", "after"],
            "stylistic/padded-blocks": ["error", "never"],
            "stylistic/quote-props": ["error", "consistent-as-needed", {"keywords": true, "numbers": true}],
            "stylistic/quotes": ["error", "double", {"allowTemplateLiterals": true}],
            "stylistic/rest-spread-spacing": ["error", "never"],
            "stylistic/semi": ["error", "always"],
            "stylistic/semi-spacing": ["error", {"before": false, "after": true}],
            "stylistic/space-before-blocks": ["error"],
            "stylistic/space-before-function-paren": ["error", "never"],
            "stylistic/space-in-parens": ["error", "never"],
            "stylistic/space-infix-ops": ["error", {"int32Hint": false}],
            "stylistic/space-unary-ops": ["error"],
            "stylistic/spaced-comment": ["error", "always"],
            "stylistic/template-curly-spacing": ["error", "never"],
            "stylistic/template-tag-spacing": ["error", "never"],
            "stylistic/wrap-iife": ["error", "outside"],
            "stylistic/yield-star-spacing": ["error", {"before": false, "after": true}],
            // jest:recommended
            "jest/expect-expect": "warn",
            "jest/no-alias-methods": "error",
            "jest/no-commented-out-tests": "warn",
            "jest/no-conditional-expect": "error",
            "jest/no-deprecated-functions": "error",
            "jest/no-disabled-tests": "warn",
            "jest/no-done-callback": "error",
            "jest/no-export": "error",
            "jest/no-focused-tests": "error",
            "jest/no-identical-title": "error",
            "jest/no-interpolation-in-snapshots": "error",
            "jest/no-jasmine-globals": "error",
            "jest/no-mocks-import": "error",
            "jest/no-standalone-expect": "error",
            "jest/no-test-prefixes": "error",
            "jest/valid-describe-callback": "error",
            "jest/valid-expect": "error",
            "jest/valid-expect-in-promise": "error",
            "jest/valid-title": "error"
        },
    }
];
