var EPackageFileTag = {
    PACKAGE_FILE_TAG: 0x9E2A83C1,
    PACKAGE_FILE_TAG_SWAPPED: 0xC1832A9E
};

var EUnrealEngineObjectUE4Version = {
    VER_UE4_OLDEST_LOADABLE_PACKAGE: {value: 214, comment: "Oldest package managed by Unreal Engine"},
    VER_UE4_BLUEPRINT_VARS_NOT_READ_ONLY: {value: 215, comment: "Removed restriction on blueprint-exposed variables from being read-only"},
    VER_UE4_STATIC_MESH_STORE_NAV_COLLISION: {value: 216, comment: "Added manually serialized element to UStaticMesh (precalculated nav collision)"},
    VER_UE4_ATMOSPHERIC_FOG_DECAY_NAME_CHANGE: {value: 217, comment: "Changed property name for atmospheric fog"},
    VER_UE4_SCENECOMP_TRANSLATION_TO_LOCATION: {value: 218, comment: "Change many properties/functions from Translation to Location"},
    VER_UE4_MATERIAL_ATTRIBUTES_REORDERING: {value: 219, comment: "Material attributes reordering"},
    VER_UE4_COLLISION_PROFILE_SETTING: {value: 220, comment: "Collision Profile setting has been added, and all components that exists has to be properly upgraded"},
    VER_UE4_BLUEPRINT_SKEL_TEMPORARY_TRANSIENT: {value: 221, comment: "Making the blueprint's skeleton class transient"},
    VER_UE4_BLUEPRINT_SKEL_SERIALIZED_AGAIN: {value: 222, comment: "Making the blueprint's skeleton class serialized again"},
    VER_UE4_BLUEPRINT_SETS_REPLICATION: {value: 223, comment: "Blueprint now controls replication settings again"},
    VER_UE4_WORLD_LEVEL_INFO: {value: 224, comment: "Added level info used by World browser"},
    VER_UE4_AFTER_CAPSULE_HALF_HEIGHT_CHANGE: {value: 225, comment: "Changed capsule height to capsule half-height (afterwards)"},
    VER_UE4_ADDED_NAMESPACE_AND_KEY_DATA_TO_FTEXT: {value: 226, comment: "Added Namepace, GUID (Key) and Flags to FText"},
    VER_UE4_ATTENUATION_SHAPES: {value: 227, comment: "Attenuation shapes"},
    VER_UE4_LIGHTCOMPONENT_USE_IES_TEXTURE_MULTIPLIER_ON_NON_IES_BRIGHTNESS: {value: 228, comment: "Use IES texture multiplier even when IES brightness is not being used"},
    VER_UE4_REMOVE_INPUT_COMPONENTS_FROM_BLUEPRINTS: {value: 229, comment: "Removed InputComponent as a blueprint addable component"},
    VER_UE4_VARK2NODE_USE_MEMBERREFSTRUCT: {value: 230, comment: "Use an FMemberReference struct in UK2Node_Variable"},
    VER_UE4_REFACTOR_MATERIAL_EXPRESSION_SCENECOLOR_AND_SCENEDEPTH_INPUTS: {value: 231, comment: "Refactored material expression inputs for UMaterialExpressionSceneColor and UMaterialExpressionSceneDepth"},
    VER_UE4_SPLINE_MESH_ORIENTATION: {value: 232, comment: "Spline meshes changed from Z forwards to configurable"},
    VER_UE4_REVERB_EFFECT_ASSET_TYPE: {value: 233, comment: "Added ReverbEffect asset type"},
    VER_UE4_MAX_TEXCOORD_INCREASED: {value: 234, comment: "changed max texcoords from 4 to 8"},
    VER_UE4_SPEEDTREE_STATICMESH: {value: 235, comment: "static meshes changed to support SpeedTrees"},
    VER_UE4_LANDSCAPE_COMPONENT_LAZY_REFERENCES: {value: 236, comment: "Landscape component reference between landscape component and collision component"},
    VER_UE4_SWITCH_CALL_NODE_TO_USE_MEMBER_REFERENCE: {value: 237, comment: "Refactored UK2Node_CallFunction to use FMemberReference"},
    VER_UE4_ADDED_SKELETON_ARCHIVER_REMOVAL: {value: 238, comment: "Added fixup step to remove skeleton class references from blueprint objects"},
    VER_UE4_ADDED_SKELETON_ARCHIVER_REMOVAL_SECOND_TIME: {value: 239, comment: "See above, take 2."},
    VER_UE4_BLUEPRINT_SKEL_CLASS_TRANSIENT_AGAIN: {value: 240, comment: "Making the skeleton class on blueprints transient"},
    VER_UE4_ADD_COOKED_TO_UCLASS: {value: 241, comment: "UClass knows if it's been cooked"},
    VER_UE4_DEPRECATED_STATIC_MESH_THUMBNAIL_PROPERTIES_REMOVED: {value: 242, comment: "Deprecated static mesh thumbnail properties were removed"},
    VER_UE4_COLLECTIONS_IN_SHADERMAPID: {value: 243, comment: "Added collections in material shader map ids"},
    VER_UE4_REFACTOR_MOVEMENT_COMPONENT_HIERARCHY: {value: 244, comment: "Renamed some Movement Component properties, added PawnMovementComponent"},
    VER_UE4_FIX_TERRAIN_LAYER_SWITCH_ORDER: {value: 245, comment: "Swap UMaterialExpressionTerrainLayerSwitch::LayerUsed/LayerNotUsed the correct way round"},
    VER_UE4_ALL_PROPS_TO_CONSTRAINTINSTANCE: {value: 246, comment: "Remove URB_ConstraintSetup"},
    VER_UE4_LOW_QUALITY_DIRECTIONAL_LIGHTMAPS: {value: 247, comment: "Low quality directional lightmaps"},
    VER_UE4_ADDED_NOISE_EMITTER_COMPONENT: {value: 248, comment: "Added NoiseEmitterComponent and removed related Pawn properties."},
    VER_UE4_ADD_TEXT_COMPONENT_VERTICAL_ALIGNMENT: {value: 249, comment: "Add text component vertical alignment"},
    VER_UE4_ADDED_FBX_ASSET_IMPORT_DATA: {value: 250, comment: "Added AssetImportData for FBX asset types, deprecating SourceFilePath and SourceFileTimestamp"},
    VER_UE4_REMOVE_LEVELBODYSETUP: {value: 251, comment: "Remove LevelBodySetup from ULevel"},
    VER_UE4_REFACTOR_CHARACTER_CROUCH: {value: 252, comment: "Refactor character crouching"},
    VER_UE4_SMALLER_DEBUG_MATERIALSHADER_UNIFORM_EXPRESSIONS: {value: 253, comment: "Trimmed down material shader debug information."},
    VER_UE4_APEX_CLOTH: {value: 254, comment: "APEX Clothing"},
    VER_UE4_SAVE_COLLISIONRESPONSE_PER_CHANNEL: {value: 255, comment: "we should rename to match ECollisionChannel"},
    VER_UE4_ADDED_LANDSCAPE_SPLINE_EDITOR_MESH: {value: 256, comment: "Added Landscape Spline editor meshes"},
    VER_UE4_CHANGED_MATERIAL_REFACTION_TYPE: {value: 257, comment: "Fixup input expressions for reading from refraction material attributes."},
    VER_UE4_REFACTOR_PROJECTILE_MOVEMENT: {value: 258, comment: "Refactor projectile movement, along with some other movement component work."},
    VER_UE4_REMOVE_PHYSICALMATERIALPROPERTY: {value: 259, comment: "Remove PhysicalMaterialProperty and replace with user defined enum"},
    VER_UE4_PURGED_FMATERIAL_COMPILE_OUTPUTS: {value: 260, comment: "Removed all compile outputs from FMaterial"},
    VER_UE4_ADD_COOKED_TO_LANDSCAPE: {value: 261, comment: "Ability to save cooked PhysX meshes to Landscape"},
    VER_UE4_CONSUME_INPUT_PER_BIND: {value: 262, comment: "Change how input component consumption works"},
    VER_UE4_SOUND_CLASS_GRAPH_EDITOR: {value: 263, comment: "Added new Graph based SoundClass Editor"},
    VER_UE4_FIXUP_TERRAIN_LAYER_NODES: {value: 264, comment: "Fixed terrain layer node guids which was causing artifacts"},
    VER_UE4_RETROFIT_CLAMP_EXPRESSIONS_SWAP: {value: 265, comment: "Added clamp min/max swap check to catch older materials"},
    VER_UE4_REMOVE_LIGHT_MOBILITY_CLASSES: {value: 266, comment: "Remove static/movable/stationary light classes"},
    VER_UE4_REFACTOR_PHYSICS_BLENDING: {value: 267, comment: "Refactor the way physics blending works to allow partial blending"},
    VER_UE4_WORLD_LEVEL_INFO_UPDATED: {value: 268, comment: "WorldLevelInfo: Added reference to parent level and streaming distance"},
    VER_UE4_STATIC_SKELETAL_MESH_SERIALIZATION_FIX: {value: 269, comment: "Fixed cooking of skeletal/static meshes due to bad serialization logic"},
    VER_UE4_REMOVE_STATICMESH_MOBILITY_CLASSES: {value: 270, comment: "Removal of InterpActor and PhysicsActor"},
    VER_UE4_REFACTOR_PHYSICS_TRANSFORMS: {value: 271, comment: "Refactor physics transforms"},
    VER_UE4_REMOVE_ZERO_TRIANGLE_SECTIONS: {value: 272, comment: "Remove zero triangle sections from static meshes and compact material indices."},
    VER_UE4_CHARACTER_MOVEMENT_DECELERATION: {value: 273, comment: "Add param for deceleration in character movement instead of using acceleration."},
    VER_UE4_CAMERA_ACTOR_USING_CAMERA_COMPONENT: {value: 274, comment: "Made ACameraActor use a UCameraComponent for parameter storage, etc..."},
    VER_UE4_CHARACTER_MOVEMENT_DEPRECATE_PITCH_ROLL: {value: 275, comment: "Deprecated some pitch/roll properties in CharacterMovementComponent"},
    VER_UE4_REBUILD_TEXTURE_STREAMING_DATA_ON_LOAD: {value: 276, comment: "Rebuild texture streaming data on load for uncooked builds"},
    VER_UE4_SUPPORT_32BIT_STATIC_MESH_INDICES: {value: 277, comment: "Add support for 32 bit index buffers for static meshes."},
    VER_UE4_ADDED_CHUNKID_TO_ASSETDATA_AND_UPACKAGE: {value: 278, comment: "Added streaming install ChunkID to AssetData and UPackage"},
    VER_UE4_CHARACTER_DEFAULT_MOVEMENT_BINDINGS: {value: 279, comment: "Add flag to control whether Character blueprints receive default movement bindings."},
    VER_UE4_APEX_CLOTH_LOD: {value: 280, comment: "APEX Clothing LOD Info"},
    VER_UE4_ATMOSPHERIC_FOG_CACHE_DATA: {value: 281, comment: "Added atmospheric fog texture data to be general"},
    VAR_UE4_ARRAY_PROPERTY_INNER_TAGS: {value: 282, comment: "Arrays serialize their inner's tags"},
    VER_UE4_KEEP_SKEL_MESH_INDEX_DATA: {value: 283, comment: "Skeletal mesh index data is kept in memory in game to support mesh merging."},
    VER_UE4_BODYSETUP_COLLISION_CONVERSION: {value: 284, comment: "Added compatibility for the body instance collision change"},
    VER_UE4_REFLECTION_CAPTURE_COOKING: {value: 285, comment: "Reflection capture cooking"},
    VER_UE4_REMOVE_DYNAMIC_VOLUME_CLASSES: {value: 286, comment: "Removal of DynamicTriggerVolume, DynamicBlockingVolume, DynamicPhysicsVolume"},
    VER_UE4_STORE_HASCOOKEDDATA_FOR_BODYSETUP: {value: 287, comment: "Store an additional flag in the BodySetup to indicate whether there is any cooked data to load"},
    VER_UE4_REFRACTION_BIAS_TO_REFRACTION_DEPTH_BIAS: {value: 288, comment: "Changed name of RefractionBias to RefractionDepthBias."},
    VER_UE4_REMOVE_SKELETALPHYSICSACTOR: {value: 289, comment: "Removal of SkeletalPhysicsActor"},
    VER_UE4_PC_ROTATION_INPUT_REFACTOR: {value: 290, comment: "PlayerController rotation input refactor"},
    VER_UE4_LANDSCAPE_PLATFORMDATA_COOKING: {value: 291, comment: "Landscape Platform Data cooking"},
    VER_UE4_CREATEEXPORTS_CLASS_LINKING_FOR_BLUEPRINTS: {value: 292, comment: "Added call for linking classes in CreateExport to ensure memory is initialized properly"},
    VER_UE4_REMOVE_NATIVE_COMPONENTS_FROM_BLUEPRINT_SCS: {value: 293, comment: "Remove native component nodes from the blueprint SimpleConstructionScript"},
    VER_UE4_REMOVE_SINGLENODEINSTANCE: {value: 294, comment: "Removal of Single Node Instance"},
    VER_UE4_CHARACTER_BRAKING_REFACTOR: {value: 295, comment: "Character movement braking changes"},
    VER_UE4_VOLUME_SAMPLE_LOW_QUALITY_SUPPORT: {value: 296, comment: "Supported low quality lightmaps in volume samples"},
    VER_UE4_SPLIT_TOUCH_AND_CLICK_ENABLES: {value: 297, comment: "Split bEnableTouchEvents out from bEnableClickEvents"},
    VER_UE4_HEALTH_DEATH_REFACTOR: {value: 298, comment: "Health/Death refactor"},
    VER_UE4_SOUND_NODE_ENVELOPER_CURVE_CHANGE: {value: 299, comment: "Moving USoundNodeEnveloper from UDistributionFloatConstantCurve to FRichCurve"},
    VER_UE4_POINT_LIGHT_SOURCE_RADIUS: {value: 300, comment: "Moved SourceRadius to UPointLightComponent"},
    VER_UE4_SCENE_CAPTURE_CAMERA_CHANGE: {value: 301, comment: "Scene capture actors based on camera actors."},
    VER_UE4_MOVE_SKELETALMESH_SHADOWCASTING: {value: 302, comment: "Moving SkeletalMesh shadow casting flag from LoD details to material"},
    VER_UE4_CHANGE_SETARRAY_BYTECODE: {value: 303, comment: "Changing bytecode operators for creating arrays"},
    VER_UE4_MATERIAL_INSTANCE_BASE_PROPERTY_OVERRIDES: {value: 304, comment: "Material Instances overriding base material properties."},
    VER_UE4_COMBINED_LIGHTMAP_TEXTURES: {value: 305, comment: "Combined top/bottom lightmap textures"},
    VER_UE4_BUMPED_MATERIAL_EXPORT_GUIDS: {value: 306, comment: "Forced material lightmass guids to be regenerated"},
    VER_UE4_BLUEPRINT_INPUT_BINDING_OVERRIDES: {value: 307, comment: "Allow overriding of parent class input bindings"},
    VER_UE4_FIXUP_BODYSETUP_INVALID_CONVEX_TRANSFORM: {value: 308, comment: "Fix up convex invalid transform"},
    VER_UE4_FIXUP_STIFFNESS_AND_DAMPING_SCALE: {value: 309, comment: "Fix up scale of physics stiffness and damping value"},
    VER_UE4_REFERENCE_SKELETON_REFACTOR: {value: 310, comment: "Convert USkeleton and FBoneContrainer to using FReferenceSkeleton."},
    VER_UE4_K2NODE_REFERENCEGUIDS: {value: 311, comment: "Adding references to variable, function, and macro nodes to be able to update to renamed values"},
    VER_UE4_FIXUP_ROOTBONE_PARENT: {value: 312, comment: "Fix up the 0th bone's parent bone index."},
    VER_UE4_TEXT_RENDER_COMPONENTS_WORLD_SPACE_SIZING: {value: 313, comment: "llow setting of TextRenderComponents size in world space."},
    VER_UE4_MATERIAL_INSTANCE_BASE_PROPERTY_OVERRIDES_PHASE_2: {value: 314, comment: "Material Instances overriding base material properties #2."},
    VER_UE4_CLASS_NOTPLACEABLE_ADDED: {value: 315, comment: "CLASS_Placeable becomes CLASS_NotPlaceable"},
    VER_UE4_WORLD_LEVEL_INFO_LOD_LIST: {value: 316, comment: "Added LOD info list to a world tile description"},
    VER_UE4_CHARACTER_MOVEMENT_VARIABLE_RENAMING_1: {value: 317, comment: "CharacterMovement variable naming refactor"},
    VER_UE4_FSLATESOUND_CONVERSION: {value: 318, comment: "FName properties containing sound names converted to FSlateSound properties"},
    VER_UE4_WORLD_LEVEL_INFO_ZORDER: {value: 319, comment: "Added ZOrder to a world tile description"},
    VER_UE4_PACKAGE_REQUIRES_LOCALIZATION_GATHER_FLAGGING: {value: 320, comment: "Added flagging of localization gather requirement to packages"},
    VER_UE4_BP_ACTOR_VARIABLE_DEFAULT_PREVENTING: {value: 321, comment: "Preventing Blueprint Actor variables from having default values"},
    VER_UE4_TEST_ANIMCOMP_CHANGE: {value: 322, comment: "Preventing Blueprint Actor variables from having default values"},
    VER_UE4_EDITORONLY_BLUEPRINTS: {value: 323, comment: "Class as primary asset, name convention changed"},
    VER_UE4_EDGRAPHPINTYPE_SERIALIZATION: {value: 324, comment: "Custom serialization for FEdGraphPinType"},
    VER_UE4_NO_MIRROR_BRUSH_MODEL_COLLISION: {value: 325, comment: "Stop generating 'mirrored' cooked mesh for Brush and Model components"},
    VER_UE4_CHANGED_CHUNKID_TO_BE_AN_ARRAY_OF_CHUNKIDS: {value: 326, comment: "Changed ChunkID to be an array of IDs."},
    VER_UE4_WORLD_NAMED_AFTER_PACKAGE: {value: 327, comment: "Worlds have been renamed from \"TheWorld\" to be named after the package containing them"},
    VER_UE4_SKY_LIGHT_COMPONENT: {value: 328, comment: "Added sky light component"},
    VER_UE4_WORLD_LAYER_ENABLE_DISTANCE_STREAMING: {value: 329, comment: "Added Enable distance streaming flag to FWorldTileLayer"},
    VER_UE4_REMOVE_ZONES_FROM_MODEL: {value: 330, comment: "Remove visibility/zone information from UModel"},
    VER_UE4_FIX_ANIMATIONBASEPOSE_SERIALIZATION: {value: 331, comment: "Fix base pose serialization"},
    VER_UE4_SUPPORT_8_BONE_INFLUENCES_SKELETAL_MESHES: {value: 332, comment: "Support for up to 8 skinning influences per vertex on skeletal meshes (on non-gpu vertices)"},
    VER_UE4_ADD_OVERRIDE_GRAVITY_FLAG: {value: 333, comment: "Add explicit bOverrideGravity to world settings"},
    VER_UE4_SUPPORT_GPUSKINNING_8_BONE_INFLUENCES: {value: 334, comment: "Support for up to 8 skinning influences per vertex on skeletal meshes (on gpu vertices)"},
    VER_UE4_ANIM_SUPPORT_NONUNIFORM_SCALE_ANIMATION: {value: 335, comment: "Supporting nonuniform scale animation"},
    VER_UE4_ENGINE_VERSION_OBJECT: {value: 336, comment: "Engine version is stored as a FEngineVersion object rather than changelist number"},
    VER_UE4_PUBLIC_WORLDS: {value: 337, comment: "World assets now have RF_Public"},
    VER_UE4_SKELETON_GUID_SERIALIZATION: {value: 338, comment: "Skeleton Guid"},
    VER_UE4_CHARACTER_MOVEMENT_WALKABLE_FLOOR_REFACTOR: {value: 339, comment: "Character movement WalkableFloor refactor"},
    VER_UE4_INVERSE_SQUARED_LIGHTS_DEFAULT: {value: 340, comment: "Lights default to inverse squared"},
    VER_UE4_DISABLED_SCRIPT_LIMIT_BYTECODE: {value: 341, comment: "Disabled SCRIPT_LIMIT_BYTECODE_TO_64KB"},
    VER_UE4_PRIVATE_REMOTE_ROLE: {value: 342, comment: "Made remote role private, exposed bReplicates"},
    VER_UE4_FOLIAGE_STATIC_MOBILITY: {value: 343, comment: "Fix up old foliage components to have static mobility (superseded by VER_UE4_FOLIAGE_MOVABLE_MOBILITY)"},
    VER_UE4_BUILD_SCALE_VECTOR: {value: 344, comment: "Change BuildScale from a float to a vector"},
    VER_UE4_FOLIAGE_COLLISION: {value: 345, comment: "After implementing foliage collision, need to disable collision on old foliage instances"},
    VER_UE4_SKY_BENT_NORMAL: {value: 346, comment: "Added sky bent normal to indirect lighting cache"},
    VER_UE4_LANDSCAPE_COLLISION_DATA_COOKING: {value: 347, comment: "Added cooking for landscape collision data"},
    VER_UE4_MORPHTARGET_CPU_TANGENTZDELTA_FORMATCHANGE: {value: 348, comment: "we still convert all to FVector in CPU time whenever any calculation"},
    VER_UE4_SOFT_CONSTRAINTS_USE_MASS: {value: 349, comment: "Soft constraint limits will implicitly use the mass of the bodies"},
    VER_UE4_REFLECTION_DATA_IN_PACKAGES: {value: 350, comment: "Reflection capture data saved in packages"},
    VER_UE4_FOLIAGE_MOVABLE_MOBILITY: {value: 351, comment: "Fix up old foliage components to have movable mobility (superseded by VER_UE4_FOLIAGE_STATIC_LIGHTING_SUPPORT)"},
    VER_UE4_UNDO_BREAK_MATERIALATTRIBUTES_CHANGE: {value: 352, comment: "Undo BreakMaterialAttributes changes as it broke old content"},
    VER_UE4_ADD_CUSTOMPROFILENAME_CHANGE: {value: 353, comment: "Now Default custom profile name isn't NONE anymore due to copy/paste not working properly with it"},
    VER_UE4_FLIP_MATERIAL_COORDS: {value: 354, comment: "Permanently flip and scale material expression coordinates"},
    VER_UE4_MEMBERREFERENCE_IN_PINTYPE: {value: 355, comment: "PinSubCategoryMemberReference added to FEdGraphPinType"},
    VER_UE4_VEHICLES_UNIT_CHANGE: {value: 356, comment: "Vehicles use Nm for Torque instead of cm and RPM instead of rad/s"},
    VER_UE4_ANIMATION_REMOVE_NANS: {value: 357, comment: "now importing should detect NaNs, so we should not have NaNs in source data"},
    VER_UE4_SKELETON_ASSET_PROPERTY_TYPE_CHANGE: {value: 358, comment: "Change skeleton preview attached assets property type"},
    VER_UE4_FIX_BLUEPRINT_VARIABLE_FLAGS: {value: 359, comment: "when they shouldn't"},
    VER_UE4_VEHICLES_UNIT_CHANGE2: {value: 360, comment: "Vehicles use Nm for Torque instead of cm and RPM instead of rad/s part two (missed conversion for some variables"},
    VER_UE4_UCLASS_SERIALIZE_INTERFACES_AFTER_LINKING: {value: 361, comment: "Changed order of interface class serialization"},
    VER_UE4_STATIC_MESH_SCREEN_SIZE_LODS: {value: 362, comment: "Change from LOD distances to display factors"},
    VER_UE4_FIX_MATERIAL_COORDS: {value: 363, comment: "Requires test of material coords to ensure they're saved correctly"},
    VER_UE4_SPEEDTREE_WIND_V7: {value: 364, comment: "Changed SpeedTree wind presets to v7"},
    VER_UE4_LOAD_FOR_EDITOR_GAME: {value: 365, comment: "NeedsLoadForEditorGame added"},
    VER_UE4_SERIALIZE_RICH_CURVE_KEY: {value: 366, comment: "Manual serialization of FRichCurveKey to save space"},
    VER_UE4_MOVE_LANDSCAPE_MICS_AND_TEXTURES_WITHIN_LEVEL: {value: 367, comment: "Change the outer of ULandscapeMaterialInstanceConstants and Landscape-related textures to the level in which they reside"},
    VER_UE4_FTEXT_HISTORY: {value: 368, comment: "FTexts have creation history data, removed Key, Namespaces, and SourceString"},
    VER_UE4_FIX_MATERIAL_COMMENTS: {value: 369, comment: "Shift comments to the left to contain expressions properly"},
    VER_UE4_STORE_BONE_EXPORT_NAMES: {value: 370, comment: "Bone names stored as FName means that we can't guarantee the correct case on export, now we store a separate string for export purposes only"},
    VER_UE4_MESH_EMITTER_INITIAL_ORIENTATION_DISTRIBUTION: {value: 371, comment: "changed mesh emitter initial orientation to distribution"},
    VER_UE4_DISALLOW_FOLIAGE_ON_BLUEPRINTS: {value: 372, comment: "Foliage on blueprints causes crashes"},
    VER_UE4_FIXUP_MOTOR_UNITS: {value: 373, comment: "change motors to use revolutions per second instead of rads/second"},
    VER_UE4_DEPRECATED_MOVEMENTCOMPONENT_MODIFIED_SPEEDS: {value: 374, comment: "deprecated MovementComponent functions including \"ModifiedMaxSpeed\" et al"},
    VER_UE4_RENAME_CANBECHARACTERBASE: {value: 375, comment: "rename CanBeCharacterBase"},
    VER_UE4_GAMEPLAY_TAG_CONTAINER_TAG_TYPE_CHANGE: {value: 376, comment: "Change GameplayTagContainers to have FGameplayTags instead of FNames; Required to fix-up native serialization"},
    VER_UE4_FOLIAGE_SETTINGS_TYPE: {value: 377, comment: "Change from UInstancedFoliageSettings to UFoliageType, and change the api from being keyed on UStaticMesh* to UFoliageType*"},
    VER_UE4_STATIC_SHADOW_DEPTH_MAPS: {value: 378, comment: "Lights serialize static shadow depth maps"},
    VER_UE4_ADD_TRANSACTIONAL_TO_DATA_ASSETS: {value: 379, comment: "Add RF_Transactional to data assets, fixing undo problems when editing them"},
    VER_UE4_ADD_LB_WEIGHTBLEND: {value: 380, comment: "Change LB_AlphaBlend to LB_WeightBlend in ELandscapeLayerBlendType"},
    VER_UE4_ADD_ROOTCOMPONENT_TO_FOLIAGEACTOR: {value: 381, comment: "Add root component to an foliage actor, all foliage cluster components will be attached to a root"},
    VER_UE4_FIX_MATERIAL_PROPERTY_OVERRIDE_SERIALIZE: {value: 382, comment: "FMaterialInstanceBasePropertyOverrides didn't use proper UObject serialize"},
    VER_UE4_ADD_LINEAR_COLOR_SAMPLER: {value: 383, comment: "Addition of linear color sampler. color sample type is changed to linear sampler if source texture !sRGB"},
    VER_UE4_ADD_STRING_ASSET_REFERENCES_MAP: {value: 384, comment: "Added StringAssetReferencesMap to support renames of FStringAssetReference properties."},
    VER_UE4_BLUEPRINT_USE_SCS_ROOTCOMPONENT_SCALE: {value: 385, comment: "Apply scale from SCS RootComponent details in the Blueprint Editor to new actor instances at construction time"},
    VER_UE4_LEVEL_STREAMING_DRAW_COLOR_TYPE_CHANGE: {value: 386, comment: "Changed level streaming to have a linear color since the visualization doesn't gamma correct."},
    VER_UE4_CLEAR_NOTIFY_TRIGGERS: {value: 387, comment: "Cleared end triggers from non-state anim notifies"},
    VER_UE4_SKELETON_ADD_SMARTNAMES: {value: 388, comment: "Convert old curve names stored in anim assets into skeleton smartnames"},
    VER_UE4_ADDED_CURRENCY_CODE_TO_FTEXT: {value: 389, comment: "Added the currency code field to FTextHistory_AsCurrency"},
    VER_UE4_ENUM_CLASS_SUPPORT: {value: 390, comment: "Added support for C++11 enum classes"},
    VER_UE4_FIXUP_WIDGET_ANIMATION_CLASS: {value: 391, comment: "Fixup widget animation class"},
    VER_UE4_SOUND_COMPRESSION_TYPE_ADDED: {value: 392, comment: "USoundWave objects now contain details about compression scheme used."},
    VER_UE4_AUTO_WELDING: {value: 393, comment: "Bodies will automatically weld when attached"},
    VER_UE4_RENAME_CROUCHMOVESCHARACTERDOWN: {value: 394, comment: "Rename UCharacterMovementComponent::bCrouchMovesCharacterDown"},
    VER_UE4_LIGHTMAP_MESH_BUILD_SETTINGS: {value: 395, comment: "Lightmap parameters in FMeshBuildSettings"},
    VER_UE4_RENAME_SM3_TO_ES3_1: {value: 396, comment: "Rename SM3 to ES3_1 and updates featurelevel material node selector"},
    VER_UE4_DEPRECATE_UMG_STYLE_ASSETS: {value: 397, comment: "Deprecated separate style assets for use in UMG"},
    VER_UE4_POST_DUPLICATE_NODE_GUID: {value: 398, comment: "Duplicating Blueprints will regenerate NodeGuids after this version"},
    VER_UE4_RENAME_CAMERA_COMPONENT_VIEW_ROTATION: {value: 399, comment: "Rename UCameraComponent::bUseControllerViewRotation to bUsePawnViewRotation (and change the default value)"},
    VER_UE4_CASE_PRESERVING_FNAME: {value: 400, comment: "Changed FName to be case preserving"},
    VER_UE4_RENAME_CAMERA_COMPONENT_CONTROL_ROTATION: {value: 401, comment: "Rename UCameraComponent::bUsePawnViewRotation to bUsePawnControlRotation"},
    VER_UE4_FIX_REFRACTION_INPUT_MASKING: {value: 402, comment: "Fix bad refraction material attribute masks"},
    VER_UE4_GLOBAL_EMITTER_SPAWN_RATE_SCALE: {value: 403, comment: "A global spawn rate for emitters."},
    VER_UE4_CLEAN_DESTRUCTIBLE_SETTINGS: {value: 404, comment: "Cleanup destructible mesh settings"},
    VER_UE4_CHARACTER_MOVEMENT_UPPER_IMPACT_BEHAVIOR: {value: 405, comment: "CharacterMovementComponent refactor of AdjustUpperHemisphereImpact and deprecation of some associated vars."},
    VER_UE4_BP_MATH_VECTOR_EQUALITY_USES_EPSILON: {value: 406, comment: "Changed Blueprint math equality functions for vectors and rotators to operate as a \"nearly\" equals rather than \"exact\""},
    VER_UE4_FOLIAGE_STATIC_LIGHTING_SUPPORT: {value: 407, comment: "Static lighting support was re-added to foliage, and mobility was returned to static"},
    VER_UE4_SLATE_COMPOSITE_FONTS: {value: 408, comment: "Added composite fonts to Slate font info"},
    VER_UE4_REMOVE_SAVEGAMESUMMARY: {value: 409, comment: "Remove UDEPRECATED_SaveGameSummary, required for UWorld::Serialize"},
    VER_UE4_REMOVE_SKELETALMESH_COMPONENT_BODYSETUP_SERIALIZATION: {value: 410, comment: "emove bodyseutp serialization from skeletal mesh component"},
    VER_UE4_SLATE_BULK_FONT_DATA: {value: 411, comment: "Made Slate font data use bulk data to store the embedded font data"},
    VER_UE4_ADD_PROJECTILE_FRICTION_BEHAVIOR: {value: 412, comment: "Add new friction behavior in ProjectileMovementComponent."},
    VER_UE4_MOVEMENTCOMPONENT_AXIS_SETTINGS: {value: 413, comment: "Add axis settings enum to MovementComponent."},
    VER_UE4_GRAPH_INTERACTIVE_COMMENTBUBBLES: {value: 414, comment: "Switch to new interactive comments, requires boundry conversion to preserve previous states"},
    VER_UE4_LANDSCAPE_SERIALIZE_PHYSICS_MATERIALS: {value: 415, comment: "Landscape serializes physical materials for collision objects"},
    VER_UE4_RENAME_WIDGET_VISIBILITY: {value: 416, comment: "Rename Visiblity on widgets to Visibility"},
    VER_UE4_ANIMATION_ADD_TRACKCURVES: {value: 417, comment: "add track curves for animation"},
    VER_UE4_MONTAGE_BRANCHING_POINT_REMOVAL: {value: 418, comment: "Removed BranchingPoints from AnimMontages and converted them to regular AnimNotifies."},
    VER_UE4_BLUEPRINT_ENFORCE_CONST_IN_FUNCTION_OVERRIDES: {value: 419, comment: "Enforce const-correctness in Blueprint implementations of native C++ const class methods"},
    VER_UE4_ADD_PIVOT_TO_WIDGET_COMPONENT: {value: 420, comment: "Added pivot to widget components, need to load old versions as a 0,0 pivot, new default is 0.5,0.5"},
    VER_UE4_PAWN_AUTO_POSSESS_AI: {value: 421, comment: "Added finer control over when AI Pawns are automatically possessed. Also renamed Pawn.AutoPossess to Pawn.AutoPossessPlayer indicate this was a setting for players and not AI."},
    VER_UE4_FTEXT_HISTORY_DATE_TIMEZONE: {value: 422, comment: "Added serialization of timezone to FTextHistory for AsDate operations."},
    VER_UE4_SORT_ACTIVE_BONE_INDICES: {value: 423, comment: "Sort ActiveBoneIndices on lods so that we can avoid doing it at run time"},
    VER_UE4_PERFRAME_MATERIAL_UNIFORM_EXPRESSIONS: {value: 424, comment: "Added per-frame material uniform expressions"},
    VER_UE4_MIKKTSPACE_IS_DEFAULT: {value: 425, comment: "Make MikkTSpace the default tangent space calculation method for static meshes."},
    VER_UE4_LANDSCAPE_GRASS_COOKING: {value: 426, comment: "Only applies to cooked files, grass cooking support."},
    VER_UE4_FIX_SKEL_VERT_ORIENT_MESH_PARTICLES: {value: 427, comment: "Fixed code for using the bOrientMeshEmitters property."},
    VER_UE4_LANDSCAPE_STATIC_SECTION_OFFSET: {value: 428, comment: "Do not change landscape section offset on load under world composition"},
    VER_UE4_ADD_MODIFIERS_RUNTIME_GENERATION: {value: 429, comment: "New options for navigation data runtime generation (static, modifiers only, dynamic)"},
    VER_UE4_MATERIAL_MASKED_BLENDMODE_TIDY: {value: 430, comment: "Tidied up material's handling of masked blend mode."},
    VER_UE4_MERGED_ADD_MODIFIERS_RUNTIME_GENERATION_TO_4_7_DEPRECATED: {value: 431, comment: "Original version of VER_UE4_MERGED_ADD_MODIFIERS_RUNTIME_GENERATION_TO_4_7; renumbered to prevent blocking promotion in main."},
    VER_UE4_AFTER_MERGED_ADD_MODIFIERS_RUNTIME_GENERATION_TO_4_7_DEPRECATED: {value: 432, comment: "Original version of VER_UE4_AFTER_MERGED_ADD_MODIFIERS_RUNTIME_GENERATION_TO_4_7; renumbered to prevent blocking promotion in main."},
    VER_UE4_MERGED_ADD_MODIFIERS_RUNTIME_GENERATION_TO_4_7: {value: 433, comment: "After merging VER_UE4_ADD_MODIFIERS_RUNTIME_GENERATION into 4.7 branch"},
    VER_UE4_AFTER_MERGING_ADD_MODIFIERS_RUNTIME_GENERATION_TO_4_7: {value: 434, comment: "After merging VER_UE4_ADD_MODIFIERS_RUNTIME_GENERATION into 4.7 branch"},
    VER_UE4_SERIALIZE_LANDSCAPE_GRASS_DATA: {value: 435, comment: "Landscape grass weightmap data is now generated in the editor and serialized."},
    VER_UE4_OPTIONALLY_CLEAR_GPU_EMITTERS_ON_INIT: {value: 436, comment: "New property to optionally prevent gpu emitters clearing existing particles on Init()."},
    VER_UE4_SERIALIZE_LANDSCAPE_GRASS_DATA_MATERIAL_GUID: {value: 437, comment: "Also store the Material guid with the landscape grass data"},
    VER_UE4_BLUEPRINT_GENERATED_CLASS_COMPONENT_TEMPLATES_PUBLIC: {value: 438, comment: "Make sure that all template components from blueprint generated classes are flagged as public"},
    VER_UE4_ACTOR_COMPONENT_CREATION_METHOD: {value: 439, comment: "Split out creation method on ActorComponents to distinguish between native, instance, and simple or user construction script"},
    VER_UE4_K2NODE_EVENT_MEMBER_REFERENCE: {value: 440, comment: "K2Node_Event now uses FMemberReference for handling references"},
    VER_UE4_STRUCT_GUID_IN_PROPERTY_TAG: {value: 441, comment: "FPropertyTag stores GUID of struct"},
    VER_UE4_REMOVE_UNUSED_UPOLYS_FROM_UMODEL: {value: 442, comment: "Remove unused UPolys from UModel cooked content"},
    VER_UE4_REBUILD_HIERARCHICAL_INSTANCE_TREES: {value: 443, comment: "This doesn't do anything except trigger a rebuild on HISMC cluster trees, in this case to get a good \"occlusion query\" level"},
    VER_UE4_PACKAGE_SUMMARY_HAS_COMPATIBLE_ENGINE_VERSION: {value: 444, comment: "Package summary includes an CompatibleWithEngineVersion field, separately to the version it's saved with"},
    VER_UE4_TRACK_UCS_MODIFIED_PROPERTIES: {value: 445, comment: "Track UCS modified properties on Actor Components"},
    VER_UE4_LANDSCAPE_SPLINE_CROSS_LEVEL_MESHES: {value: 446, comment: "Allowed landscape spline meshes to be stored into landscape streaming levels rather than the spline's level"},
    VER_UE4_DEPRECATE_USER_WIDGET_DESIGN_SIZE: {value: 447, comment: "Deprecate the variables used for sizing in the designer on UUserWidget"},
    VER_UE4_ADD_EDITOR_VIEWS: {value: 448, comment: "Make the editor views array dynamically sized"},
    VER_UE4_FOLIAGE_WITH_ASSET_OR_CLASS: {value: 449, comment: "Updated foliage to work with either FoliageType assets or blueprint classes"},
    VER_UE4_BODYINSTANCE_BINARY_SERIALIZATION: {value: 450, comment: "Allows PhysicsSerializer to serialize shapes and actors for faster load times"},
    VER_UE4_SERIALIZE_BLUEPRINT_EVENTGRAPH_FASTCALLS_IN_UFUNCTION: {value: 451, comment: "Added fastcall data serialization directly in UFunction"},
    VER_UE4_INTERPCURVE_SUPPORTS_LOOPING: {value: 452, comment: "Changes to USplineComponent and FInterpCurve"},
    VER_UE4_MATERIAL_INSTANCE_BASE_PROPERTY_OVERRIDES_DITHERED_LOD_TRANSITION: {value: 453, comment: "Material Instances overriding base material LOD transitions"},
    VER_UE4_SERIALIZE_LANDSCAPE_ES2_TEXTURES: {value: 454, comment: "Serialize ES2 textures separately rather than overwriting the properties used on other platforms"},
    VER_UE4_CONSTRAINT_INSTANCE_MOTOR_FLAGS: {value: 455, comment: "Constraint motor velocity is broken into per-component"},
    VER_UE4_SERIALIZE_PINTYPE_CONST: {value: 456, comment: "Serialize bIsConst in FEdGraphPinType"},
    VER_UE4_LIBRARY_CATEGORIES_AS_FTEXT: {value: 457, comment: "Change UMaterialFunction::LibraryCategories to LibraryCategoriesText (old assets were saved before auto-conversion of FArrayProperty was possible)"},
    VER_UE4_SKIP_DUPLICATE_EXPORTS_ON_SAVE_PACKAGE: {value: 458, comment: "Check for duplicate exports while saving packages."},
    VER_UE4_SERIALIZE_TEXT_IN_PACKAGES: {value: 459, comment: "Pre-gathering of gatherable, localizable text in packages to optimize text gathering operation times"},
    VER_UE4_ADD_BLEND_MODE_TO_WIDGET_COMPONENT: {value: 460, comment: "Added pivot to widget components, need to load old versions as a 0,0 pivot, new default is 0.5,0.5"},
    VER_UE4_NEW_LIGHTMASS_PRIMITIVE_SETTING: {value: 461, comment: "Added lightmass primitive setting"},
    VER_UE4_REPLACE_SPRING_NOZ_PROPERTY: {value: 462, comment: "Deprecate NoZSpring property on spring nodes to be replaced with TranslateZ property"},
    VER_UE4_TIGHTLY_PACKED_ENUMS: {value: 463, comment: "Keep enums tight and serialize their values as pairs of FName and value. Don't insert dummy values."},
    VER_UE4_ASSET_IMPORT_DATA_AS_JSON: {value: 464, comment: "Changed Asset import data to serialize file meta data as JSON"},
    VER_UE4_TEXTURE_LEGACY_GAMMA: {value: 465, comment: "Legacy gamma support for textures."},
    VER_UE4_ADDED_NATIVE_SERIALIZATION_FOR_IMMUTABLE_STRUCTURES: {value: 466, comment: "Added WithSerializer for basic native structures like FVector, FColor etc to improve serialization performance"},
    VER_UE4_DEPRECATE_UMG_STYLE_OVERRIDES: {value: 467, comment: "Deprecated attributes that override the style on UMG widgets"},
    VER_UE4_STATIC_SHADOWMAP_PENUMBRA_SIZE: {value: 468, comment: "Shadowmap penumbra size stored"},
    VER_UE4_NIAGARA_DATA_OBJECT_DEV_UI_FIX: {value: 469, comment: "Fix BC on Niagara effects from the data object and dev UI changes."},
    VER_UE4_FIXED_DEFAULT_ORIENTATION_OF_WIDGET_COMPONENT: {value: 470, comment: "Fixed the default orientation of widget component so it faces down +x"},
    VER_UE4_REMOVED_MATERIAL_USED_WITH_UI_FLAG: {value: 471, comment: "Removed bUsedWithUI flag from UMaterial and replaced it with a new material domain for UI"},
    VER_UE4_CHARACTER_MOVEMENT_ADD_BRAKING_FRICTION: {value: 472, comment: "Added braking friction separate from turning friction."},
    VER_UE4_BSP_UNDO_FIX: {value: 473, comment: "Removed TTransArrays from UModel"},
    VER_UE4_DYNAMIC_PARAMETER_DEFAULT_VALUE: {value: 474, comment: "Added default value to dynamic parameter."},
    VER_UE4_STATIC_MESH_EXTENDED_BOUNDS: {value: 475, comment: "Added ExtendedBounds to StaticMesh"},
    VER_UE4_ADDED_NON_LINEAR_TRANSITION_BLENDS: {value: 476, comment: "Added non-linear blending to anim transitions, deprecating old types"},
    VER_UE4_AO_MATERIAL_MASK: {value: 477, comment: "AO Material Mask texture"},
    VER_UE4_NAVIGATION_AGENT_SELECTOR: {value: 478, comment: "Replaced navigation agents selection with single structure"},
    VER_UE4_MESH_PARTICLE_COLLISIONS_CONSIDER_PARTICLE_SIZE: {value: 479, comment: "Mesh particle collisions consider particle size."},
    VER_UE4_BUILD_MESH_ADJ_BUFFER_FLAG_EXPOSED: {value: 480, comment: "Adjacency buffer building no longer automatically handled based on triangle count, user-controlled"},
    VER_UE4_MAX_ANGULAR_VELOCITY_DEFAULT: {value: 481, comment: "Change the default max angular velocity"},
    VER_UE4_APEX_CLOTH_TESSELLATION: {value: 482, comment: "Build Adjacency index buffer for clothing tessellation"},
    VER_UE4_DECAL_SIZE: {value: 483, comment: "Added DecalSize member, solved backward compatibility"},
    VER_UE4_KEEP_ONLY_PACKAGE_NAMES_IN_STRING_ASSET_REFERENCES_MAP: {value: 484, comment: "Keep only package names in StringAssetReferencesMap"},
    VER_UE4_COOKED_ASSETS_IN_EDITOR_SUPPORT: {value: 485, comment: "Support sound cue not saving out editor only data"},
    VER_UE4_DIALOGUE_WAVE_NAMESPACE_AND_CONTEXT_CHANGES: {value: 486, comment: "Updated dialogue wave localization gathering logic."},
    VER_UE4_MAKE_ROT_RENAME_AND_REORDER: {value: 487, comment: "Renamed MakeRot MakeRotator and rearranged parameters."},
    VER_UE4_K2NODE_VAR_REFERENCEGUIDS: {value: 488, comment: "K2Node_Variable will properly have the VariableReference Guid set if available"},
    VER_UE4_SOUND_CONCURRENCY_PACKAGE: {value: 489, comment: "Added support for sound concurrency settings structure and overrides"},
    VER_UE4_USERWIDGET_DEFAULT_FOCUSABLE_FALSE: {value: 490, comment: "Changing the default value for focusable user widgets to false"},
    VER_UE4_BLUEPRINT_CUSTOM_EVENT_CONST_INPUT: {value: 491, comment: "Custom event nodes implicitly set 'const' on array and non-array pass-by-reference input params"},
    VER_UE4_USE_LOW_PASS_FILTER_FREQ: {value: 492, comment: "Renamed HighFrequencyGain to LowPassFilterFrequency"},
    VER_UE4_NO_ANIM_BP_CLASS_IN_GAMEPLAY_CODE: {value: 493, comment: "UAnimBlueprintGeneratedClass can be replaced by a dynamic class. Use TSubclassOf<UAnimInstance> instead."},
    VER_UE4_SCS_STORES_ALLNODES_ARRAY: {value: 494, comment: "The SCS keeps a list of all nodes in its hierarchy rather than recursively building it each time it is requested"},
    VER_UE4_FBX_IMPORT_DATA_RANGE_ENCAPSULATION: {value: 495, comment: "Moved StartRange and EndRange in UFbxAnimSequenceImportData to use FInt32Interval"},
    VER_UE4_CAMERA_COMPONENT_ATTACH_TO_ROOT: {value: 496, comment: "Adding a new root scene component to camera component"},
    VER_UE4_INSTANCED_STEREO_UNIFORM_UPDATE: {value: 497, comment: "Updating custom material expression nodes for instanced stereo implementation"},
    VER_UE4_STREAMABLE_TEXTURE_MIN_MAX_DISTANCE: {value: 498, comment: "Texture streaming min and max distance to handle HLOD"},
    VER_UE4_INJECT_BLUEPRINT_STRUCT_PIN_CONVERSION_NODES: {value: 499, comment: "Fixing up invalid struct-to-struct pin connections by injecting available conversion nodes"},
    VER_UE4_INNER_ARRAY_TAG_INFO: {value: 500, comment: "Saving tag data for Array Property's inner property"},
    VER_UE4_FIX_SLOT_NAME_DUPLICATION: {value: 501, comment: "Fixed duplicating slot node names in skeleton due to skeleton preload on compile"},
    VER_UE4_STREAMABLE_TEXTURE_AABB: {value: 502, comment: "Texture streaming using AABBs instead of Spheres"},
    VER_UE4_PROPERTY_GUID_IN_PROPERTY_TAG: {value: 503, comment: "FPropertyTag stores GUID of property"},
    VER_UE4_NAME_HASHES_SERIALIZED: {value: 504, comment: "Name table hashes are calculated and saved out rather than at load time"},
    VER_UE4_INSTANCED_STEREO_UNIFORM_REFACTOR: {value: 505, comment: "Updating custom material expression nodes for instanced stereo implementation refactor"},
    VER_UE4_COMPRESSED_SHADER_RESOURCES: {value: 506, comment: "Added compression to the shader resource for memory savings"},
    VER_UE4_PRELOAD_DEPENDENCIES_IN_COOKED_EXPORTS: {value: 507, comment: "Cooked files contain the dependency graph for the event driven loader (the serialization is largely independent of the use of the new loader)"},
    VER_UE4_TEMPLATEINDEX_IN_COOKED_EXPORTS: {value: 508, comment: "Cooked files contain the TemplateIndex used by the event driven loader (the serialization is largely independent of the use of the new loader, i.e. this will be null if cooking for the old loader)"},
    VER_UE4_PROPERTY_TAG_SET_MAP_SUPPORT: {value: 509, comment: "FPropertyTag includes contained type(s) for Set and Map properties:"},
    VER_UE4_ADDED_SEARCHABLE_NAMES: {value: 510, comment: "Added SearchableNames to the package summary and asset registry"},
    VER_UE4_64BIT_EXPORTMAP_SERIALSIZES: {value: 511, comment: "Increased size of SerialSize and SerialOffset in export map entries to 64 bit, allow support for bigger files"},
    VER_UE4_SKYLIGHT_MOBILE_IRRADIANCE_MAP: {value: 512, comment: "Sky light stores IrradianceMap for mobile renderer."},
    VER_UE4_ADDED_SWEEP_WHILE_WALKING_FLAG: {value: 513, comment: "Added flag to control sweep behavior while walking in UCharacterMovementComponent."},
    VER_UE4_ADDED_SOFT_OBJECT_PATH: {value: 514, comment: "StringAssetReference changed to SoftObjectPath and swapped to serialize as a name+string instead of a string"},
    VER_UE4_POINTLIGHT_SOURCE_ORIENTATION: {value: 515, comment: "Changed the source orientation of point lights to match spot lights (z axis)"},
    VER_UE4_ADDED_PACKAGE_SUMMARY_LOCALIZATION_ID: {value: 516, comment: "LocalizationId has been added to the package summary (editor-only)"},
    VER_UE4_FIX_WIDE_STRING_CRC: {value: 517, comment: "Fixed case insensitive hashes of wide strings containing character values from 128-255"},
    VER_UE4_ADDED_PACKAGE_OWNER: {value: 518, comment: "Added package owner to allow private references"},
    VER_UE4_SKINWEIGHT_PROFILE_DATA_LAYOUT_CHANGES: {value: 519, comment: "Changed the data layout for skin weight profile data"},
    VER_UE4_NON_OUTER_PACKAGE_IMPORT: {value: 520, comment: "Added import that can have package different than their outer"},
    VER_UE4_ASSETREGISTRY_DEPENDENCYFLAGS: {value: 521, comment: "Added DependencyFlags to AssetRegistry"},
    VER_UE4_CORRECT_LICENSEE_FLAG: {value: 522, comment: "Fixed corrupt licensee flag in 4.26 assets"},
    VER_UE4_AUTOMATIC_VERSION_PLUS_ONE: {value: 523, comment: "Last version +1"},
    VER_UE4_AUTOMATIC_VERSION: {value: 522, comment: "Fixed corrupt licensee flag in 4.26 assets"}
};

var EUnrealEngineObjectUE5Version = {
    VER_UE5_INITIAL_VERSION: {value: 1000, comment: "The original UE5 version, at the time this was added the UE4 version was 522, so UE5 will start from 1000 to show a clear difference"},
    VER_UE5_NAMES_REFERENCED_FROM_EXPORT_DATA: {value: 1001, comment: "Support stripping names that are not referenced from export data"},
    VER_UE5_PAYLOAD_TOC: {value: 1002, comment: "Added a payload table of contents to the package summary"},
    VER_UE5_OPTIONAL_RESOURCES: {value: 1003, comment: "Added data to identify references from and to optional package"},
    VER_UE5_LARGE_WORLD_COORDINATES: {value: 1004, comment: "Large world coordinates converts a number of core types to double components by default."},
    VER_UE5_REMOVE_OBJECT_EXPORT_PACKAGE_GUID: {value: 1005, comment: "Remove package GUID from FObjectExport"},
	VER_UE5_TRACK_OBJECT_EXPORT_IS_INHERITED: {value: 1006, comment: "Add IsInherited to the FObjectExport entry"},
	VER_UE5_FSOFTOBJECTPATH_REMOVE_ASSET_PATH_FNAMES: {value: 1007, comment: "Replace FName asset path in FSoftObjectPath with (package name, asset name) pair FTopLevelAssetPath"},
	VER_UE5_ADD_SOFTOBJECTPATH_LIST: {value: 1008, comment: "Add a soft object path list to the package summary for fast remap"},
	VER_UE5_DATA_RESOURCES: {value: 1009, comment: "Added bulk/data resource table"},
    VER_UE5_AUTOMATIC_VERSION_PLUS_ONE: {value: 1010, comment: "Last version +1"},
    VER_UE5_AUTOMATIC_VERSION: {value: 1009, comment: "Large world coordinates converts a number of core types to double components by default."}
};

/* eslint-disable */
var PackageFlags = {
    PKG_None: {value: 0x00000000, comment: "No flags"},
    PKG_NewlyCreated: {value: 0x00000001, comment: "Newly created package, not saved yet. In editor only."},
    PKG_ClientOptional: {value: 0x00000002, comment: "Purely optional for clients."},
    PKG_ServerSideOnly: {value: 0x00000004, comment: "Only needed on the server side."},
    PKG_CompiledIn: {value: 0x00000010, comment: "This package is from \"compiled in\" classes."},
    PKG_ForDiffing: {value: 0x00000020, comment: "This package was loaded just for the purposes of diffing"},
    PKG_EditorOnly: {value: 0x00000040, comment: "This is editor-only package (for example: editor module script package)"},
    PKG_Developer: {value: 0x00000080, comment: "Developer module"},
    PKG_UncookedOnly: {value: 0x00000100, comment: "Loaded only in uncooked builds (i.e. runtime in editor)"},
    PKG_Cooked: {value: 0x00000200, comment: "Package is cooked"},
    PKG_ContainsNoAsset: {value: 0x00000400, comment: "Package doesn't contain any asset object (although asset tags can be present)"},
    PKG_ExternallyReferenceable: {value: 0x00000800, comment: "(Not Implemented) Objects in this package can be referenced in a different plugin or mount point (i.e /Game -> /Engine)"},
    PKG_Unused_1000: {value: 0x00001000, comment: "Unused"},
    PKG_UnversionedProperties: {value: 0x00002000, comment: "Uses unversioned property serialization instead of versioned tagged property serialization"},
    PKG_ContainsMapData: {value: 0x00004000, comment: "Contains map data (UObjects only referenced by a single ULevel) but is stored in a different package"},
    PKG_IsSaving: {value: 0x00008000, comment: "Temporarily set on a package while it is being saved."},
    PKG_Compiling: {value: 0x00010000, comment: "package is currently being compiled"},
    PKG_ContainsMap: {value: 0x00020000, comment: "Set if the package contains a ULevel/ UWorld object"},
    PKG_RequiresLocalizationGather: {value: 0x00040000, comment: "Set if the package contains any data to be gathered by localization"},
    PKG_Unused_80000: {value: 0x00080000, comment: "Unused"},
    PKG_PlayInEditor: {value: 0x00100000, comment: "Set if the package was created for the purpose of PIE"},
    PKG_ContainsScript: {value: 0x00200000, comment: "Package is allowed to contain UClass objects"},
    PKG_DisallowExport: {value: 0x00400000, comment: "Editor should not export asset in this package"},
    PKG_Unused_800000: {value: 0x00800000, comment: "Unused"},
    PKG_Unused_1000000: {value: 0x01000000, comment: "Unused"},
    PKG_Unused_2000000: {value: 0x02000000, comment: "Unused"},
    PKG_Unused_4000000: {value: 0x04000000, comment: "Unused"},
    PKG_Unused_8000000: {value: 0x08000000, comment: "Unused"},
    PKG_DynamicImports: {value: 0x10000000, comment: "This package should resolve dynamic imports from its export at runtime."},
    PKG_RuntimeGenerated: {value: 0x20000000, comment: "This package contains elements that are runtime generated, and may not follow standard loading order rules"},
    PKG_ReloadingForCooker: {value: 0x40000000, comment: "This package is reloading in the cooker, try to avoid getting data we will never need. We won't save this package."},
    PKG_FilterEditorOnly: {value: 0x80000000, comment: "Package has editor-only data filtered out"},
    PKG_TransientFlags: {value: (0x00000001 | 0x00008000 | 0x40000000), comment: "Transient Flags are cleared when serializing to or from PackageFileSummary"}
};
/* eslint-enable */

window.EPackageFileTag = EPackageFileTag; // GULP REMOVE LINE
window.EUnrealEngineObjectUE4Version = EUnrealEngineObjectUE4Version; // GULP REMOVE LINE
window.EUnrealEngineObjectUE5Version = EUnrealEngineObjectUE5Version; // GULP REMOVE LINE
window.PackageFlags = PackageFlags; // GULP REMOVE LINE
